export type RentalType = "long" | "daily";
export type Availability = "available" | "shows" | "rented";
export type CityId = "kazan" | "saint-petersburg";

export type Property = { id:string; city:CityId; title:string; district:string; address:string; metro:string; rooms:number; area:number; floor:string; price:number; rating:string; reviews:number; status:Availability; verified:boolean; deposit:number; description:string; amenities:string[]; images:string[]; coordinates:{ lat:number; lng:number } };
export type PropertyFilters = { query:string; rooms:"all"|"1"|"2"|"3"; maxPrice:number; rentalType:RentalType; availability?:"all"|"available" };

export const propertyImage = {
  baumana:"/manus-storage/baumana-bedroom_349f8be6.jpg", yamasheva:"/manus-storage/yamasheva-living_2b256505.jpg", chistopolskaya:"/manus-storage/chistopolskaya-living_18730a34.jpg", sibirsky:"/manus-storage/sibirsky-bedroom_49331806.jpg", pobezhimova:"/manus-storage/pobezhimova-kitchen_d929a936.jpg", dekabristov:"/manus-storage/dekabristov-openplan_96f04818.jpg",
  living:"/manus-storage/rentbez-apartment-living-room_b7676013.jpg", kitchen:"/manus-storage/rentbez-apartment-kitchen_70e1d15f.jpg", bedroom:"/manus-storage/rentbez-apartment-bedroom_ea8e0dde.jpg",
} as const;

const make = (value: Omit<Property,"verified"|"deposit"|"status"> & Partial<Pick<Property,"verified"|"deposit"|"status">>): Property => ({ verified:true, deposit:0, status:"available", ...value });
export const properties:Property[] = [
  make({id:"baumana-1",city:"kazan",title:"1-комнатная квартира на Баумана",district:"Вахитовский район, Казань",address:"ул. Баумана, 15",metro:"Кремлёвская, 5 мин",rooms:1,area:38,floor:"4 из 9",price:28000,rating:"4.9",reviews:12,description:"Светлая однокомнатная квартира в историческом центре города. Свежий ремонт, встроенная кухня, качественная мебель и бытовая техника.",amenities:["Стиральная машина","Посудомоечная машина","Кондиционер","Интернет 100 Мбит/с","Мебель","Холодильник"],images:[propertyImage.baumana,propertyImage.kitchen,propertyImage.bedroom],coordinates:{lat:55.7879,lng:49.1224}}),
  make({id:"yamasheva-2",city:"kazan",title:"2-комнатная квартира на Ямашева",district:"Ново-Савиновский район, Казань",address:"пр. Ямашева, 101",metro:"Яшьлек, 8 мин",rooms:2,area:56,floor:"7 из 14",price:38000,rating:"4.8",reviews:8,description:"Просторная двухкомнатная квартира с удобной планировкой, балконом с видом на парк и готовой инфраструктурой для семьи.",amenities:["Стиральная машина","Кондиционер","Интернет 100 Мбит/с","Мебель","Холодильник","Телевизор"],images:[propertyImage.yamasheva,propertyImage.bedroom,propertyImage.living],coordinates:{lat:55.8233,lng:49.1077}}),
  make({id:"chistopolskaya-studio",city:"kazan",title:"Студия, Советский район",district:"Советский район, Казань",address:"ул. Чистопольская, 67",metro:"Горки, 12 мин",rooms:1,area:28,floor:"3 из 16",price:22000,rating:"4.7",reviews:9,status:"shows",description:"Светлая студия с необходимой техникой, мебелью и понятными условиями долгосрочной аренды.",amenities:["Стиральная машина","Интернет 100 Мбит/с","Холодильник","Лифт"],images:[propertyImage.chistopolskaya,propertyImage.living,propertyImage.bedroom],coordinates:{lat:55.8232,lng:49.1192}}),
  make({id:"sibirsky-2",city:"kazan",title:"2-комн. квартира, Приволжский",district:"Приволжский район, Казань",address:"ул. Сибирский тракт, 34",metro:"Проспект Победы, 6 мин",rooms:2,area:52,floor:"5 из 10",price:35000,rating:"4.9",reviews:14,status:"shows",description:"Квартира с удобной планировкой, закрытым двором и готовой инфраструктурой для спокойной аренды.",amenities:["Стиральная машина","Посудомоечная машина","Кондиционер","Закрытый двор","Лифт"],images:[propertyImage.sibirsky,propertyImage.bedroom,propertyImage.kitchen],coordinates:{lat:55.7943,lng:49.1820}}),
  make({id:"pobezhimova-3",city:"kazan",title:"3-комн. квартира, Авиастроительный",district:"Авиастроительный район, Казань",address:"ул. Побежимова, 47",metro:"нет метро",rooms:3,area:78,floor:"6 из 12",price:48000,rating:"4.6",reviews:6,status:"shows",description:"Просторная квартира для семьи: светлые комнаты, тихий двор и понятные условия долгосрочной аренды.",amenities:["Интернет 100 Мбит/с","Кондиционер","Парковка","Лифт"],images:[propertyImage.pobezhimova,propertyImage.living,propertyImage.bedroom],coordinates:{lat:55.8640,lng:49.0800}}),
  make({id:"dekabristov-1",city:"kazan",title:"1-комн. квартира, Московский район",district:"Московский район, Казань",address:"ул. Декабристов, 180",metro:"нет метро",rooms:1,area:40,floor:"2 из 5",price:26000,rating:"4.8",reviews:11,status:"shows",description:"Аккуратная квартира с мебелью и бытовой техникой недалеко от городской инфраструктуры.",amenities:["Стиральная машина","Телевизор","Балкон","Холодильник"],images:[propertyImage.dekabristov,propertyImage.living,propertyImage.kitchen],coordinates:{lat:55.8315,lng:49.0836}}),
  make({id:"nevsky-1",city:"saint-petersburg",title:"1-комн. квартира на Невском",district:"Центральный район, Санкт-Петербург",address:"Невский пр., 81",metro:"Маяковская, 3 мин",rooms:1,area:40,floor:"4 из 7",price:75000,rating:"4.9",reviews:18,description:"Светлая квартира в центре Петербурга рядом с Невским проспектом и городской инфраструктурой.",amenities:["Стиральная машина","Кондиционер","Интернет","Мебель"],images:[propertyImage.baumana,propertyImage.living,propertyImage.bedroom],coordinates:{lat:59.9315,lng:30.3547}}),
  make({id:"komendantsky-2",city:"saint-petersburg",title:"2-комн. квартира на Комендантском",district:"Приморский район, Санкт-Петербург",address:"Комендантский пр., 58",metro:"Комендантский проспект, 9 мин",rooms:2,area:56,floor:"9 из 18",price:58000,rating:"4.8",reviews:10,description:"Современная двухкомнатная квартира с готовой кухней и удобной транспортной доступностью.",amenities:["Посудомоечная машина","Интернет","Лифт","Балкон"],images:[propertyImage.yamasheva,propertyImage.kitchen,propertyImage.bedroom],coordinates:{lat:60.0085,lng:30.2602}}),
  make({id:"moskovsky-spb-1",city:"saint-petersburg",title:"1-комн. квартира на Московском",district:"Московский район, Санкт-Петербург",address:"Московский пр., 183–185",metro:"Московская, 5 мин",rooms:1,area:37,floor:"8 из 16",price:65000,rating:"4.7",reviews:7,status:"shows",description:"Квартира с мебелью, техникой и понятными условиями долгосрочной аренды рядом с метро.",amenities:["Стиральная машина","Холодильник","Кондиционер","Лифт"],images:[propertyImage.chistopolskaya,propertyImage.living,propertyImage.kitchen],coordinates:{lat:59.8515,lng:30.3212}}),
];
export const availabilityLabel:Record<Availability,string> = {available:"Проверено",shows:"Проверено",rented:"Сдана"};
export function filterProperties(source:Property[], filters:PropertyFilters) { if(filters.rentalType!=="long") return []; const q=filters.query.trim().toLocaleLowerCase("ru-RU"); return source.filter(p => (!q||[p.title,p.district,p.address,p.metro].join(" ").toLocaleLowerCase("ru-RU").includes(q))&&(filters.rooms==="all"||p.rooms===Number(filters.rooms))&&p.price<=filters.maxPrice&&(filters.availability!=="available"||p.status==="available")&&p.status!=="rented"); }
export function calculateOwnerEconomics(rate:number) { const ownerIncome=Math.max(0,Math.round(Number.isFinite(rate)?rate:0)); const serviceFee=Math.round(ownerIncome*.1); return {ownerIncome,tenantMonthlyTotal:ownerIncome+serviceFee,serviceFee}; }
export function formatRubles(value:number) { return new Intl.NumberFormat("ru-RU",{maximumFractionDigits:0,style:"currency",currency:"RUB"}).format(value); }
