/** Figma fidelity: светлый интерфейс Аренда БЕЗ; компактная desktop/mobile-сводка собственника с честным статусом без серверной модерации. */
import { ArrowRight, CalendarClock, CheckCircle2, Clock3, Home, Plus, UserRoundCheck } from "lucide-react";
import { Link } from "wouter";
import { AppShell } from "@/components/AppShell";
import { Seo } from "@/components/Seo";
import { formatRubles, properties } from "@/lib/domain";

export default function OwnerPage() {
  const property = properties[1];
  return <AppShell><Seo title="Кабинет собственника" description="Демонстрационная сводка объекта и заявок собственника в Аренде БЕЗ." /><section className="owner-page"><div className="owner-heading"><div><p className="eyebrow">Кабинет собственника</p><h1>Добрый день, Анна</h1><p>Статусы здесь показаны как интерфейсный сценарий. Реальная модерация и SLA появятся с серверной частью.</p></div><Link href="/landlords" className="button button--primary"><Plus size={16} /> Добавить квартиру</Link></div><div className="owner-stats"><article><Home /><div><span>Активные объекты</span><strong>1</strong></div></article><article><UserRoundCheck /><div><span>Новые заявки</span><strong>2</strong></div></article><article><CalendarClock /><div><span>Ближайший показ</span><strong>Завтра, 18:30</strong></div></article></div><section className="owner-property"><div className="owner-property__image"><img src={property.images[0]} width="600" height="400" alt={`Интерьер: ${property.title}`} /></div><div className="owner-property__body"><div><p className="eyebrow">На подбор</p><h2>{property.title}</h2><p>{property.address} · {property.area} м²</p></div><div className="owner-property__rate"><span>Ваша ставка</span><strong>{formatRubles(property.price)} / мес</strong></div><div className="owner-property__progress"><div><span>Готовность к публикации</span><b>75%</b></div><progress max="100" value="75">75%</progress><p>Следующий шаг: подтвердить финальные фотографии и условия показа.</p></div><Link href={`/listing/${property.id}`} className="text-link">Открыть публичную карточку <ArrowRight size={15} /></Link></div></section><section className="owner-activity"><div><p className="eyebrow">Заявки</p><h2>Что происходит с объектом</h2></div><div className="activity-list"><article><Clock3 /><div><strong>Анкета Ирины получена</strong><p>Ожидает предварительной проверки менеджером</p></div><span>Сегодня, 10:40</span></article><article><CheckCircle2 /><div><strong>Показ предложен Максиму</strong><p>Предварительный слот: четверг, 19:00</p></div><span>Вчера</span></article></div></section></section></AppShell>;
}
