import { Heart, MapPin, Star } from "lucide-react";
import { Link } from "wouter";
import { availabilityLabel, formatRubles, type Property } from "@/lib/domain";
import { useFavorites } from "@/contexts/FavoritesContext";

export function PropertyCard({ property }: { property: Property }) {
  const { isFavorite, toggleFavorite } = useFavorites();
  const saved = isFavorite(property.id);
  return <article className="property-card"><button type="button" className={`favorite-button ${saved ? "is-saved" : ""}`} aria-label={saved ? `Убрать «${property.title}» из избранного` : `Добавить «${property.title}» в избранное`} aria-pressed={saved} onClick={() => toggleFavorite(property.id)}><Heart size={18} fill={saved ? "currentColor" : "none"} aria-hidden="true" /></button><Link href={`/listing/${property.id}`} className="property-card__image-link" aria-label={`Открыть: ${property.title}`}><img src={property.images[0]} alt={`Интерьер: ${property.title}`} width="600" height="400" loading="lazy" decoding="async" className="property-card__image" /><span className={`status-badge status-badge--${property.status}`}>Без залога</span>{property.verified && <span className="verified-badge">{availabilityLabel[property.status]}</span>}</Link><div className="property-card__body"><div className="property-card__meta"><span>{property.rooms}-комн.</span><span>{property.area} м²</span><span>{property.floor}</span></div><Link href={`/listing/${property.id}`} className="property-card__title">{property.title}</Link><p className="property-card__address"><MapPin size={14} aria-hidden="true" /> {property.address}</p><p className="property-card__rating"><Star size={14} fill="currentColor" aria-hidden="true" /> {property.rating} <span>({property.reviews} отзывов)</span> · {property.district.replace(", Казань", "")}</p><p className="property-card__price">{formatRubles(property.price)} <span>/мес</span></p><p className="property-card__fee">+ {formatRubles(Math.round(property.price * .1))} сервисный сбор</p></div></article>;
}
